import React,{useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {ContentAction,ContentExtras,ContentDocument,FAQItem,TutorialStep} from '../types';

type Props={value?:ContentExtras;onChange:(value:ContentExtras)=>void};
const emptyAction=():ContentAction=>({id:`a-${Date.now()}-${Math.random()}`,label:'',type:'external',target:'',newTab:true});
const emptyDoc=():ContentDocument=>({id:`d-${Date.now()}-${Math.random()}`,name:'',description:'',type:'PDF',url:'',download:false});
const emptyFaq=():FAQItem=>({id:`f-${Date.now()}-${Math.random()}`,question:'',answer:''});
const emptyStep=():TutorialStep=>({id:`s-${Date.now()}-${Math.random()}`,title:'',text:'',image:'',videoUrl:'',linkUrl:'',documentUrl:''});
const merge=(x:ContentExtras):ContentExtras=>({...x});
export default function ContentExtrasEditor({value,onChange}:Props){
 const [x,setX]=useState<ContentExtras>(()=>({actions:[],documents:[],faqs:[],related:[],...value}));
 const update=(patch:Partial<ContentExtras>)=>{const next=merge({...x,...patch});setX(next);onChange(next)};
 const actions=x.actions||[]; const docs=x.documents||[]; const faqs=x.faqs||[]; const steps=x.tutorial?.steps||[];
 const updateAction=(id:string,p:Partial<ContentAction>)=>update({actions:actions.map(a=>a.id===id?{...a,...p}:a)});
 const updateDoc=(id:string,p:Partial<ContentDocument>)=>update({documents:docs.map(d=>d.id===id?{...d,...p}:d)});
 const updateFaq=(id:string,p:Partial<FAQItem>)=>update({faqs:faqs.map(f=>f.id===id?{...f,...p}:f)});
 const updateStep=(id:string,p:Partial<TutorialStep>)=>update({tutorial:{ title:x.tutorial?.title ?? 'Como utilizar', description:x.tutorial?.description ?? '', steps: steps.map(s=>s.id===id?{...s,...p}:s) }});
 return <div className="content-extras-editor">
   <details open className="extras-section"><summary>Acções e botões</summary><div className="extras-body"><p className="extras-help">Escolha o texto e destino de cada botão. Só aparece publicamente quando estiver preenchido.</p>{actions.map(a=><div className="extras-row" key={a.id}><input value={a.label} onChange={e=>updateAction(a.id,{label:e.target.value})} placeholder="Texto do botão"/><select value={a.type} onChange={e=>updateAction(a.id,{type:e.target.value as any})}><option value="external">Link externo</option><option value="internal">Página interna</option><option value="page">Âncora / página</option><option value="video">Vídeo</option><option value="document">Documento</option><option value="form">Formulário</option></select><input value={a.target} onChange={e=>updateAction(a.id,{target:e.target.value})} placeholder="URL, #secção ou destino"/><label className="check inline-check"><input type="checkbox" checked={a.newTab!==false} onChange={e=>updateAction(a.id,{newTab:e.target.checked})}/> nova aba</label><button type="button" className="icon-btn danger" onClick={()=>update({actions:actions.filter(z=>z.id!==a.id)})}><Trash2 size={14}/></button></div>)}<button type="button" className="admin-secondary" onClick={()=>update({actions:[...actions,emptyAction()]})}><Plus size={14}/> Adicionar acção</button></div></details>
   <details className="extras-section"><summary>Vídeo / demonstração</summary><div className="extras-body"><div className="form-grid"><label className="admin-field"><span>URL do vídeo</span><input value={x.video?.url||''} onChange={e=>update({video:{...(x.video||{title:'Demonstração'}),url:e.target.value}})} placeholder="YouTube, Vimeo ou MP4"/></label><label className="admin-field"><span>Título</span><input value={x.video?.title||''} onChange={e=>update({video:{...(x.video||{url:''}),title:e.target.value}})} placeholder="Assistir à demonstração"/></label></div><label className="admin-field"><span>Descrição</span><textarea value={x.video?.description||''} onChange={e=>update({video:{...(x.video||{url:'',title:''}),description:e.target.value}})} placeholder="O que o vídeo mostra?"/></label><label className="admin-field"><span>Imagem de capa (URL)</span><input value={x.video?.thumbnail||''} onChange={e=>update({video:{...(x.video||{url:'',title:''}),thumbnail:e.target.value}})} placeholder="https://..."/></label>{x.video?.url&&<button type="button" className="danger-text" onClick={()=>update({video:undefined})}><Trash2 size={14}/> Remover vídeo</button>}</div></details>
   <details className="extras-section"><summary>Tutorial / guia de utilização</summary><div className="extras-body"><div className="form-grid"><label className="admin-field"><span>Título do tutorial</span><input value={x.tutorial?.title||''} onChange={e=>update({tutorial:{ title:e.target.value, description:x.tutorial?.description ?? '', steps:x.tutorial?.steps ?? [] }})} placeholder="Como utilizar"/></label><label className="admin-field"><span>Descrição</span><input value={x.tutorial?.description||''} onChange={e=>update({tutorial:{ title:x.tutorial?.title ?? 'Como utilizar', description:e.target.value, steps:x.tutorial?.steps ?? [] }})} placeholder="Guia rápido"/></label></div>{steps.map((s,i)=><div className="extras-subcard" key={s.id}><div className="panel-head"><strong>Passo {i+1}</strong><button type="button" className="danger-text" onClick={()=>update({tutorial:{ title:x.tutorial?.title ?? 'Como utilizar', description:x.tutorial?.description ?? '', steps:steps.filter(z=>z.id!==s.id) }})}><Trash2 size={13}/> Remover</button></div><div className="form-grid"><label className="admin-field"><span>Título</span><input value={s.title} onChange={e=>updateStep(s.id,{title:e.target.value})} placeholder="Criar a conta"/></label><label className="admin-field"><span>Imagem (URL)</span><input value={s.image||''} onChange={e=>updateStep(s.id,{image:e.target.value})} placeholder="https://..."/></label></div><label className="admin-field"><span>Texto</span><textarea value={s.text} onChange={e=>updateStep(s.id,{text:e.target.value})} placeholder="Explique este passo..."/></label><div className="form-grid"><label className="admin-field"><span>Vídeo (URL)</span><input value={s.videoUrl||''} onChange={e=>updateStep(s.id,{videoUrl:e.target.value})} placeholder="https://youtube.com/..."/></label><label className="admin-field"><span>Link</span><input value={s.linkUrl||''} onChange={e=>updateStep(s.id,{linkUrl:e.target.value})} placeholder="https://..."/></label></div><label className="admin-field"><span>Documento (URL)</span><input value={s.documentUrl||''} onChange={e=>updateStep(s.id,{documentUrl:e.target.value})} placeholder="https://..."/></label></div>)}<button type="button" className="admin-secondary" onClick={()=>update({tutorial:{ title:x.tutorial?.title ?? 'Como utilizar', description:x.tutorial?.description ?? '', steps:[...steps,emptyStep()] }})}><Plus size={14}/> Adicionar passo</button></div></details>
   <details className="extras-section"><summary>Documentação</summary><div className="extras-body">{docs.map(d=><div className="extras-row" key={d.id}><input value={d.name} onChange={e=>updateDoc(d.id,{name:e.target.value})} placeholder="Nome do documento"/><input value={d.type} onChange={e=>updateDoc(d.id,{type:e.target.value})} placeholder="PDF"/><input value={d.url} onChange={e=>updateDoc(d.id,{url:e.target.value})} placeholder="URL"/><label className="check inline-check"><input type="checkbox" checked={!!d.download} onChange={e=>updateDoc(d.id,{download:e.target.checked})}/> descarregar</label><button type="button" className="icon-btn danger" onClick={()=>update({documents:docs.filter(z=>z.id!==d.id)})}><Trash2 size={14}/></button></div>)}<button type="button" className="admin-secondary" onClick={()=>update({documents:[...docs,emptyDoc()]})}><Plus size={14}/> Adicionar documento</button></div></details>
   <details className="extras-section"><summary>Perguntas frequentes</summary><div className="extras-body">{faqs.map(f=><div className="extras-subcard" key={f.id}><div className="form-grid"><label className="admin-field"><span>Pergunta</span><input value={f.question} onChange={e=>updateFaq(f.id,{question:e.target.value})}/></label><label className="admin-field"><span>Resposta</span><input value={f.answer} onChange={e=>updateFaq(f.id,{answer:e.target.value})}/></label></div><button type="button" className="danger-text" onClick={()=>update({faqs:faqs.filter(z=>z.id!==f.id)})}><Trash2 size={13}/> Remover</button></div>)}<button type="button" className="admin-secondary" onClick={()=>update({faqs:[...faqs,emptyFaq()]})}><Plus size={14}/> Adicionar FAQ</button></div></details>
   <details className="extras-section"><summary>Galeria e SEO</summary><div className="extras-body"><label className="admin-field"><span>Galeria (uma URL por linha)</span><textarea value={(x.gallery||[]).join('\n')} onChange={e=>update({gallery:e.target.value.split('\n').map(v=>v.trim()).filter(Boolean)})} placeholder="https://..."/></label><div className="form-grid"><label className="admin-field"><span>SEO — título</span><input value={x.seo?.title||''} onChange={e=>update({seo:{...(x.seo||{}),title:e.target.value}})}/></label><label className="admin-field"><span>SEO — slug</span><input value={x.seo?.slug||''} onChange={e=>update({seo:{...(x.seo||{}),slug:e.target.value}})}/></label></div><label className="admin-field"><span>SEO — descrição</span><input value={x.seo?.description||''} onChange={e=>update({seo:{...(x.seo||{}),description:e.target.value}})}/></label></div></details>
 </div>;
}
